apiVersion: v1
kind: Service
metadata:
  name: postgressql-service
  namespace: postgressql
spec:
  type: NodePort
  selector:
    app: postgressql
  ports:
    - name: postgresql-port
      protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30036

